[package]
name = "ttk91"
version = "0.1.0"
authors = ["Sami Kukkonen <sami@samikukkonen.fi>"]
edition = "2018"

[dependencies]
byteorder = "1"
num-derive = "0.2"
num-traits = "0.2"
prettytable-rs = "^0.8"
nom = "=4.1.0"
combine = "3.6.7"